/**
 * KubeAid — Main Dashboard App
 *
 * Orchestrates:
 *  - Polling /status every 5s
 *  - POST /simulate  → inject failure
 *  - POST /fix       → auto-fix
 *  - OpenAI API call → AI diagnosis
 */

import { useState, useEffect, useRef, useCallback } from 'react'
import Header from './components/Header'
import SystemStatusCard from './components/SystemStatusCard'
import MetricsPanel from './components/MetricsPanel'
import AIDiagnosisPanel from './components/AIDiagnosisPanel'
import ActionPanel from './components/ActionPanel'

// ── OpenAI key — stored in .env as VITE_OPENAI_API_KEY ──────────
const OPENAI_KEY = import.meta.env.VITE_OPENAI_API_KEY

// ── How often to refresh status (ms) ────────────────────────────
const POLL_INTERVAL = 5000

export default function App() {
  // ── State ──────────────────────────────────────────────────────
  const [systemData, setSystemData] = useState({
    metrics: { cpu: 30, memory: 40, status: 'healthy' },
    logs: [],
    issue: null,
    severity: null,
    action: null,
    status: 'ok',
  })

  const [cpuHistory, setCpuHistory] = useState([30])   // rolling CPU history for mini chart
  const [diagnosis, setDiagnosis] = useState(null)     // AI diagnosis result
  const [aiLoading, setAiLoading] = useState(false)
  const [simulating, setSimulating] = useState(false)
  const [fixing, setFixing] = useState(false)
  const [lastAction, setLastAction] = useState(null)

  const pollRef = useRef(null)

  // ── Fetch /status ──────────────────────────────────────────────
  const fetchStatus = useCallback(async () => {
    try {
      const res = await fetch('/status')
      const data = await res.json()
      setSystemData(data)
      // Keep last 10 CPU readings for the chart
      setCpuHistory(prev => [...prev.slice(-9), data.metrics.cpu])
    } catch (err) {
      console.error('Failed to fetch /status:', err)
    }
  }, [])

  // ── Poll on mount ──────────────────────────────────────────────
  useEffect(() => {
    fetchStatus()
    pollRef.current = setInterval(fetchStatus, POLL_INTERVAL)
    return () => clearInterval(pollRef.current)
  }, [fetchStatus])

  // ── OpenAI Diagnosis ───────────────────────────────────────────
  const runAIDiagnosis = useCallback(async (data) => {
    if (!OPENAI_KEY) {
      // Graceful fallback if key is not configured
      setDiagnosis({
        cause: `Detected issue: ${data.issue || 'unknown'}. CPU at ${data.metrics.cpu}%, Memory at ${data.metrics.memory}%.`,
        fix: data.issue === 'high_cpu'
          ? 'Scale out pod replicas to distribute CPU load.'
          : data.issue === 'memory_spike'
            ? 'Flush unused memory caches and restart idle containers.'
            : 'Restart timed-out pods to re-establish service connectivity.',
        reasoning: 'Diagnosis generated by KubeAid rule engine (OpenAI key not configured).',
      })
      return
    }

    setAiLoading(true)
    setDiagnosis(null)
    try {
      const prompt = `You are an expert Kubernetes SRE AI.
Given the following system state, provide a concise diagnosis in JSON:
- CPU: ${data.metrics.cpu}%
- Memory: ${data.metrics.memory}%
- Status: ${data.metrics.status}
- Issue type: ${data.issue}
- Severity: ${data.severity}
- Error logs: ${data.logs.join('; ') || 'none'}

Respond ONLY with valid JSON in this exact shape:
{
  "cause": "one sentence explaining the root cause",
  "fix": "one sentence recommended fix",
  "reasoning": "one sentence technical reasoning"
}`

      const res = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${OPENAI_KEY}`,
        },
        body: JSON.stringify({
          model: 'gpt-3.5-turbo',
          messages: [{ role: 'user', content: prompt }],
          temperature: 0.3,
          max_tokens: 300,
        }),
      })

      const json = await res.json()
      const text = json.choices?.[0]?.message?.content || '{}'
      const parsed = JSON.parse(text)
      setDiagnosis(parsed)
    } catch (err) {
      console.error('OpenAI error:', err)
      setDiagnosis({
        cause: 'Could not reach OpenAI API.',
        fix: 'Check VITE_OPENAI_API_KEY in your .env file.',
        reasoning: err.message,
      })
    } finally {
      setAiLoading(false)
    }
  }, [])

  // ── POST /simulate ─────────────────────────────────────────────
  const handleSimulate = async () => {
    setSimulating(true)
    setLastAction(null)
    try {
      const res = await fetch('/simulate', { method: 'POST' })
      const data = await res.json()
      setSystemData(data)
      setCpuHistory(prev => [...prev.slice(-9), data.metrics.cpu])
      // Trigger AI diagnosis after failure injection
      if (data.issue) await runAIDiagnosis(data)
    } catch (err) {
      console.error('Simulate error:', err)
    } finally {
      setSimulating(false)
    }
  }

  // ── POST /fix ──────────────────────────────────────────────────
  const handleFix = async () => {
    setFixing(true)
    try {
      const res = await fetch('/fix', { method: 'POST' })
      const data = await res.json()
      setSystemData(data)
      setCpuHistory(prev => [...prev.slice(-9), data.metrics.cpu])
      setLastAction(data.action)
      setDiagnosis(null)
    } catch (err) {
      console.error('Fix error:', err)
    } finally {
      setFixing(false)
    }
  }

  // ── POST /reset ────────────────────────────────────────────────
  const handleReset = async () => {
    try {
      const res = await fetch('/reset', { method: 'POST' })
      const data = await res.json()
      setSystemData(data)
      setCpuHistory([30])
      setDiagnosis(null)
      setLastAction(null)
    } catch (err) {
      console.error('Reset error:', err)
    }
  }

  const { metrics, logs, issue, severity } = systemData

  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white font-sans">
      {/* Ambient glow blobs */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-[-20%] left-[-10%] w-[60vw] h-[60vw] rounded-full bg-cyan-500/5 blur-[120px]" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[50vw] h-[50vw] rounded-full bg-violet-500/5 blur-[120px]" />
      </div>

      <Header status={metrics.status} />

      <main className="relative max-w-7xl mx-auto px-6 py-8 space-y-6">
        {/* Page title */}
        <div>
          <h1 className="text-3xl font-black tracking-tight text-white">
            System Dashboard
          </h1>
          <p className="text-gray-500 text-sm mt-1">
            Detect → Diagnose → Fix → Recover
          </p>
        </div>

        {/* Top row — Status + Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <SystemStatusCard
            status={metrics.status}
            issue={issue}
            severity={severity}
          />
          <MetricsPanel
            cpu={metrics.cpu}
            memory={metrics.memory}
            cpuHistory={cpuHistory}
          />
        </div>

        {/* Bottom row — AI Diagnosis + Actions */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <AIDiagnosisPanel diagnosis={diagnosis} loading={aiLoading} />
          <ActionPanel
            onSimulate={handleSimulate}
            onFix={handleFix}
            onReset={handleReset}
            logs={logs}
            action={lastAction || systemData.action}
            simulating={simulating}
            fixing={fixing}
          />
        </div>

        {/* Footer */}
        <p className="text-center text-gray-700 text-xs pb-6">
          KubeAid v1.0 · Polling every {POLL_INTERVAL / 1000}s ·{' '}
          <span className={metrics.status === 'healthy' ? 'text-emerald-600' : 'text-red-600'}>
            {metrics.status.toUpperCase()}
          </span>
        </p>
      </main>
    </div>
  )
}
